[dev]
command = "npm start develop"
targetPort = 4321
port = 5432

[images]
remote_images = []

[build]
command = "npm run build"
publish = "dist"
functions = "functions"

  [build.environment]
  NODE_VERSION = "22.12.0"
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"

  [build.processing]

    [build.processing.html]
    pretty_urls = true

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Content-Security-Policy = "default-src 'self' https://*.piwik.pro; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.piwik.pro; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'self';"

[[headers]]
for = "/assets/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_astro/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/webudvikling"
to = "/da"
status = 301

[[redirects]]
from = "/portfolio"
to = "/da/arbejde"
status = 301

[[redirects]]
from = "/kompetencer"
to = "/da/kompetencer"
status = 301

[[redirects]]
from = "/grafik"
to = "/da"
status = 301

[[redirects]]
from = "/en"
to = "/"
status = 301

[[redirects]]
from = "/en/webudvikling"
to = "/"
status = 301

[[redirects]]
from = "/en/portfolio"
to = "/work"
status = 301

[[redirects]]
from = "/en/kompetencer"
to = "/skills"
status = 301

[[redirects]]
from = "/en/grafik"
to = "/en"
status = 301

[[redirects]]
from = "/en/artikler"
to = "/"
status = 301

[[redirects]]
from = "/artikler"
to = "/da"
status = 301

[context]

  [context.production]

    [context.production.images]
    remote_images = []

    [[context.production.headers]]
    for = "/*"

      [context.production.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
      Content-Security-Policy = "default-src 'self' https://*.piwik.pro; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.piwik.pro; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'self';"

    [[context.production.headers]]
    for = "/assets/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

    [[context.production.headers]]
    for = "/_astro/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.main]

    [context.main.images]
    remote_images = []

    [[context.main.headers]]
    for = "/*"

      [context.main.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
      Content-Security-Policy = "default-src 'self' https://*.piwik.pro; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.piwik.pro; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'self';"

    [[context.main.headers]]
    for = "/assets/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

    [[context.main.headers]]
    for = "/_astro/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"