[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22.12.0"
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"

[build.processing.html]
  pretty_urls = true

[dev]
  command = "npm start develop"
  targetPort = 4321    
  port = 5432

[functions]
  node_bundler = "esbuild"
  directory = "functions"
  included_files = ["functions/*.handlebars", "functions/*.png"]

  [functions.get-dev-tips-likes]
    external_node_modules = ["@atproto"]

  [functions.send-email]
    external_node_modules = [
      "nodemailer",
      "nodemailer-express-handlebars",
      "zod",
      "dompurify",
      "jsdom"
    ]
  
  [functions.update-dev-tips-likes]
    external_node_modules = ["@atproto"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://*.piwik.pro; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.piwik.pro; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://cdn.bsky.app; object-src 'self';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
      Content-Security-Policy = "default-src 'self' https://*.piwik.pro https://app.netlify.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.piwik.pro https://app.netlify.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://cdn.bsky.app; object-src 'self';"

[[redirects]]
  from = "/resume/Public_Resume_Lars_Ejaas_july_2024.pdf"
  to = "/resume/Public_Resume_Lars_Ejaas_june_2025.pdf"
  status = 301
  force = true  