[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22.12.0"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[build.processing.html]
  pretty_urls = true

[dev]
  command = "npm start develop"
  targetPort = 4321    
  port = 5432

[functions]
  node_bundler = "esbuild"
  directory = "functions"
  included_files = ["functions/*.handlebars", "functions/*.png"]
  external_node_modules = [
    "nodemailer",
    "nodemailer-express-handlebars",
    "zod",
    "dompurify",
    "jsdom",
  ]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; object-src 'self';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
