import fs from 'fs';
import { appRoutes } from '../i18n/appRoutes.mts';
import { sitemapPriority } from '../i18n/sitemapPriority.mts';

// Function to generate the routes dictionary
async function generateRoutes() {
  // Import the sitemap serialization function (update path accordingly)

  const routes = Object.entries(appRoutes.da).reduce(
    (acc, [page, alternate]) => {
      const firstSlug = page.split('/')[0];
      const slugLength = page.split('/').length;
      let priority = 0.7;
      const priorityObject = Object.entries(sitemapPriority).find(
        ([key]) => key === firstSlug
      );
      if (slugLength === 1 && priorityObject) {
        priority = priorityObject[1].priority;
      }
      if (slugLength > 1 && priorityObject) {
        priority =
          'subpagePriority' in priorityObject[1]
            ? priorityObject[1].subpagePriority
            : priorityObject[1].priority;
      }
      acc[page] = {
        url: page,
        alternates: [
          { url: `da/${alternate}`, lang: 'da-DK' },
          { url: page, lang: 'en-US' },
        ],
        priority,
      };
      acc[`da/${alternate}`] = {
        url: `da/${alternate}`,
        alternates: [
          { url: page, lang: 'en-US' },
          { url: `da/${alternate}`, lang: 'da-DK' },
        ],
        priority,
      };
      return acc;
    },
    {} as Record<
      string,
      {
        url: string;
        alternates: { url: string; lang: 'da-DK' | 'en-US' }[] | null;
        priority: number;
      }
    >
  );

  const autogeneratedFileMessage = `/**\n* THIS FILE IS AUTOGENERATED!\n* To make changes please run the 'generateRoutes' script from package.json.\n\nPlease be aware that the routes object may included routes that will later be excluded from the sitemap.\nExclude these by including them in 'excludedPaths' or 'rootOnlyPatterns' in 'excludeFromSitemap.json'.\n*/\n\n\n`;

  // Convert to a JavaScript module
  const output =
    autogeneratedFileMessage +
    `export const routes = ${JSON.stringify(routes, null, 2)};`;

  // Write the file to be used in Astro's build
  try {
    fs.writeFileSync('./src/utils/sitemap-routes.mjs', output, 'utf-8');
    console.info(
      '✅ Routes file: src/utils/sitemap-routes.mjs updated successfully!'
    );
  } catch (error) {
    console.error('❌ Failed to write sitemap-routes.mjs:', error);
    process.exit(1); // Exit with an error code if writing fails
  }
}

// Run the function
generateRoutes();
