import type { SkillDescriptions } from '@customTypes/skillTypes';
import GatsbyDescription from './techSkillDescriptions/Gatsby.astro';
import EmptyComponent from './techSkillDescriptions/EmptyComponent.astro';

export const skillDescriptions: SkillDescriptions = {
  accessibility: EmptyComponent,
  algolia: EmptyComponent,
  ['apollo-client']: EmptyComponent,
  astro: EmptyComponent,
  bash: EmptyComponent,
  css: EmptyComponent,
  docker: EmptyComponent,
  figma: EmptyComponent,
  gatsby: GatsbyDescription,
  git: EmptyComponent,
  github: EmptyComponent,
  gitlab: EmptyComponent,
  graphql: EmptyComponent,
  ['graphql-codegen']: EmptyComponent,
  html: EmptyComponent,
  inkscape: EmptyComponent,
  javascript: EmptyComponent,
  jest: EmptyComponent,
  mantine: EmptyComponent,
  nextjs: EmptyComponent,
  playwright: EmptyComponent,
  react: EmptyComponent,
  ['react-native']: EmptyComponent,
  ['react-testing-library']: EmptyComponent,
  redux: EmptyComponent,
  sass: EmptyComponent,
  storybook: EmptyComponent,
  strapi: EmptyComponent,
  ['styled-components']: EmptyComponent,
  svg: EmptyComponent,
  tailwind: EmptyComponent,
  typescript: EmptyComponent,
  vite: EmptyComponent,
  vscode: EmptyComponent,
  webpack: EmptyComponent,
  wordpress: EmptyComponent,
  ['wp-graphql']: EmptyComponent,
};
