import type { HTMLMarqueeDescription, SVGFileType } from '@customTypes/index';

type TechSkills = (typeof techSkillEntries)[number];

export type SkillInfo = {
  title: string;
  description: HTMLMarqueeDescription;
  imageSrc: SVGFileType;
  imageAlt: string;
  href: string;
  rating: 0 | 1 | 2 | 3 | 4 | 3.5 | 0.5 | 1.5 | 2.5 | 4.5 | 5;
};

type TechSkillItems = {
  da: Record<TechSkills, SkillInfo>;
  en: Record<TechSkills, SkillInfo>;
};

/**
 * To add a new tech skill, add a new key to the techSkillEntries array and add info to the skillsObject.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const techSkillEntries = [
  'accessibility',
  'algolia',
  'apollo-client',
  'astro',
  'bash',
  'css',
  'docker',
  'figma',
  'gatsby',
  'git',
  'github',
  'gitlab',
  'graphql',
  'graphql-codegen',
  'html',
  'inkscape',
  'javascript',
  'jest',
  'mantine',
  'nextjs',
  'playwright',
  'react',
  'react-native',
  'react-testing-library',
  'redux',
  'sass',
  'storybook',
  'strapi',
  'styled-components',
  'svg',
  'tailwind',
  'typescript',
  'vite',
  'vscode',
  'webpack',
  'wordpress',
  'wp-graphql',
] as const;

/**
 *
 * //============================================
 * @example
 * // Template for adding a new skill item:
 * title: '',
 * description: '',
 * imageSrc: '',
 * imageAlt: '',
 * href: '',
 */
export const skillsObject = {
  da: {
    accessibility: {
      title: 'Accessibility',
      description: '',
      imageSrc: 'accessibility.svg',
      imageAlt: 'Accessibility logo',
      href: 'accessibility',
      rating: 0,
    },
    algolia: {
      title: 'Algolia',
      description: '',
      imageSrc: 'algolia.svg',
      imageAlt: 'Algolia logo',
      href: 'algolia',
    },
    ['apollo-client']: {
      title: 'Apollo Client',
      description: '',
      imageSrc: 'apolloclient.svg',
      imageAlt: 'Apollo Client logo',
      href: 'apollo-client',
    },
    astro: {
      title: 'Astro',
      description: '',
      imageSrc: 'astro.svg',
      imageAlt: 'Astro logo',
      href: 'astro',
    },
    bash: {
      title: 'Bash',
      description: '',
      imageSrc: 'bash.svg',
      imageAlt: 'Bash logo',
      href: 'bash',
    },
    css: {
      title: 'CSS',
      description: '',
      imageSrc: 'css.svg',
      imageAlt: 'CSS logo',
      href: 'css',
    },
    docker: {
      title: 'Docker',
      description: '',
      imageSrc: 'docker.svg',
      imageAlt: 'Docker logo',
      href: 'docker',
    },
    figma: {
      title: 'Figma',
      description: '',
      imageSrc: 'figma.svg',
      imageAlt: 'Figma logo',
      href: 'figma',
    },
    gatsby: {
      title: 'Gatsby',
      description: '',
      imageSrc: 'gatsby.svg',
      imageAlt: 'Gatsby logo',
      href: 'gatsby',
    },
    git: {
      title: 'Git',
      description: '',
      imageSrc: 'git.svg',
      imageAlt: 'Git logo',
      href: 'git',
    },
    github: {
      title: 'Github',
      description: '',
      imageSrc: 'github.svg',
      imageAlt: 'Github logo',
      href: 'github',
    },
    gitlab: {
      title: 'Gitlab',
      description: '',
      imageSrc: 'gitlab.svg',
      imageAlt: 'Gitlab logo',
      href: 'gitlab',
    },
    graphql: {
      title: 'GraphQL',
      description: '',
      imageSrc: 'graphql.svg',
      imageAlt: 'GraphQL logo',
      href: 'graphql',
    },
    ['graphql-codegen']: {
      title: 'GraphQL Codegen',
      description: '',
      imageSrc: 'graphqlcodegen.svg',
      imageAlt: 'GraphQL Codegen logo',
      href: 'graphql-codegen',
    },
    html: {
      title: 'HTML',
      description: '',
      imageSrc: 'html.svg',
      imageAlt: 'HTML logo',
      href: 'html',
    },
    inkscape: {
      title: 'Inkscape',
      description: '',
      imageSrc: 'inkscape.svg',
      imageAlt: 'Inkscape logo',
      href: 'inkscape',
    },
    javascript: {
      title: 'JavaScript',
      description: '',
      imageSrc: 'javascript.svg',
      imageAlt: 'JavaScript logo',
      href: 'javascript',
    },
    jest: {
      title: 'Jest',
      description: '',
      imageSrc: 'jest.svg',
      imageAlt: 'Jest logo',
      href: 'jest',
    },
    mantine: {
      title: 'Mantine',
      description: '',
      imageSrc: 'mantine.svg',
      imageAlt: 'Mantine logo',
      href: 'mantine',
    },
    nextjs: {
      title: 'Next.js',
      description: '',
      imageSrc: 'nextjs.svg',
      imageAlt: 'Next.js logo',
      href: 'nextjs',
    },
    playwright: {
      title: 'Playwright',
      description: '',
      imageSrc: 'playwright.svg',
      imageAlt: 'Playwright logo',
      href: 'playwright',
    },
    react: {
      title: 'React',
      description: '',
      imageSrc: 'react.svg',
      imageAlt: 'React logo',
      href: 'react',
    },
    ['react-native']: {
      title: 'React Native',
      description: '',
      imageSrc: 'reactnative.svg',
      imageAlt: 'React Native logo',
      href: 'react-native',
    },
    ['react-testing-library']: {
      title: 'React Testing Library',
      description: '',
      imageSrc: 'reacttestinglibrary.svg',
      imageAlt: 'React Testing Library logo',
      href: 'react-testing-library',
    },
    redux: {
      title: 'Redux',
      description: '',
      imageSrc: 'redux.svg',
      imageAlt: 'Redux logo',
      href: 'redux',
    },
    sass: {
      title: 'Sass',
      description: '',
      imageSrc: 'sass.svg',
      imageAlt: 'Sass logo',
      href: 'sass',
    },
    storybook: {
      title: 'Storybook',
      description: '',
      imageSrc: 'storybook.svg',
      imageAlt: 'Storybook logo',
      href: 'storybook',
    },
    strapi: {
      title: 'Strapi',
      description: '',
      imageSrc: 'strapi.svg',
      imageAlt: 'Strapi logo',
      href: 'strapi',
    },
    ['styled-components']: {
      title: 'Styled Components',
      description: '',
      imageSrc: 'styledcomponents.svg',
      imageAlt: 'Styled Components logo',
      href: 'styled-components',
    },
    svg: {
      title: 'SVG',
      description: '',
      imageSrc: 'svg.svg',
      imageAlt: 'SVG logo',
      href: 'svg',
    },
    tailwind: {
      title: 'Tailwind',
      description: '',
      imageSrc: 'tailwind.svg',
      imageAlt: 'Tailwind logo',
      href: 'tailwind',
    },
    typescript: {
      title: 'TypeScript',
      description: '',
      imageSrc: 'typescript.svg',
      imageAlt: 'TypeScript logo',
      href: 'typescript',
    },
    vite: {
      title: 'Vite',
      description: '',
      imageSrc: 'vite.svg',
      imageAlt: 'Vite logo',
      href: 'vite',
    },
    vscode: {
      title: 'VSCode',
      description: '',
      imageSrc: 'vscode.svg',
      imageAlt: 'VSCode logo',
      href: 'vscode',
    },
    webpack: {
      title: 'Webpack',
      description: '',
      imageSrc: 'webpack.svg',
      imageAlt: 'Webpack logo',
      href: 'webpack',
    },
    wordpress: {
      title: 'WordPress',
      description: '',
      imageSrc: 'wordpress.svg',
      imageAlt: 'WordPress logo',
      href: 'wordpress',
    },
    ['wp-graphql']: {
      title: 'WPGraphQL',
      description: '',
      imageSrc: 'wpgraphql.svg',
      imageAlt: 'WPGraphQL logo',
      href: 'wp-graphql',
    },
  },
  en: {
    accessibility: {
      title: 'Accessibility',
      description: '',
      imageSrc: 'accessibility.svg',
      imageAlt: 'Accessibility logo',
      href: 'accessibility',
    },
    algolia: {
      title: 'Algolia',
      description: '',
      imageSrc: 'algolia.svg',
      imageAlt: 'Algolia logo',
      href: 'algolia',
    },
    ['apollo-client']: {
      title: 'Apollo Client',
      description: '',
      imageSrc: 'apolloclient.svg',
      imageAlt: 'Apollo Client logo',
      href: 'apollo-client',
    },
    astro: {
      title: 'Astro',
      description: '',
      imageSrc: 'astro.svg',
      imageAlt: 'Astro logo',
      href: 'astro',
    },
    bash: {
      title: 'Bash',
      description: '',
      imageSrc: 'bash.svg',
      imageAlt: 'Bash logo',
      href: 'bash',
    },
    css: {
      title: 'CSS',
      description: '',
      imageSrc: 'css.svg',
      imageAlt: 'CSS logo',
      href: 'css',
    },
    docker: {
      title: 'Docker',
      description: '',
      imageSrc: 'docker.svg',
      imageAlt: 'Docker logo',
      href: 'docker',
    },
    figma: {
      title: 'Figma',
      description: '',
      imageSrc: 'figma.svg',
      imageAlt: 'Figma logo',
      href: 'figma',
    },
    gatsby: {
      title: 'Gatsby',
      description: '',
      imageSrc: 'gatsby.svg',
      imageAlt: 'Gatsby logo',
      href: 'gatsby',
    },
    git: {
      title: 'Git',
      description: '',
      imageSrc: 'git.svg',
      imageAlt: 'Git logo',
      href: 'git',
    },
    github: {
      title: 'Github',
      description: '',
      imageSrc: 'github.svg',
      imageAlt: 'Github logo',
      href: 'github',
    },
    gitlab: {
      title: 'Gitlab',
      description: '',
      imageSrc: 'gitlab.svg',
      imageAlt: 'Gitlab logo',
      href: 'gitlab',
    },
    graphql: {
      title: 'GraphQL',
      description: '',
      imageSrc: 'graphql.svg',
      imageAlt: 'GraphQL logo',
      href: 'graphql',
    },
    ['graphql-codegen']: {
      title: 'GraphQL Codegen',
      description: '',
      imageSrc: 'graphqlcodegen.svg',
      imageAlt: 'GraphQL Codegen logo',
      href: 'graphql-codegen',
    },
    html: {
      title: 'HTML',
      description: '',
      imageSrc: 'html.svg',
      imageAlt: 'HTML logo',
      href: 'html',
    },
    inkscape: {
      title: 'Inkscape',
      description: '',
      imageSrc: 'inkscape.svg',
      imageAlt: 'Inkscape logo',
      href: 'inkscape',
    },
    javascript: {
      title: 'JavaScript',
      description: '',
      imageSrc: 'javascript.svg',
      imageAlt: 'JavaScript logo',
      href: 'javascript',
    },
    jest: {
      title: 'Jest',
      description: '',
      imageSrc: 'jest.svg',
      imageAlt: 'Jest logo',
      href: 'jest',
    },
    mantine: {
      title: 'Mantine',
      description: '',
      imageSrc: 'mantine.svg',
      imageAlt: 'Mantine logo',
      href: 'mantine',
    },
    nextjs: {
      title: 'Next.js',
      description: '',
      imageSrc: 'nextjs.svg',
      imageAlt: 'Next.js logo',
      href: 'nextjs',
    },
    playwright: {
      title: 'Playwright',
      description: '',
      imageSrc: 'playwright.svg',
      imageAlt: 'Playwright logo',
      href: 'playwright',
    },
    react: {
      title: 'React',
      description: '',
      imageSrc: 'react.svg',
      imageAlt: 'React logo',
      href: 'react',
    },
    ['react-native']: {
      title: 'React Native',
      description: '',
      imageSrc: 'reactnative.svg',
      imageAlt: 'React Native logo',
      href: 'react-native',
    },
    ['react-testing-library']: {
      title: 'React Testing Library',
      description: '',
      imageSrc: 'reacttestinglibrary.svg',
      imageAlt: 'React Testing Library logo',
      href: 'react-testing-library',
    },
    redux: {
      title: 'Redux',
      description: '',
      imageSrc: 'redux.svg',
      imageAlt: 'Redux logo',
      href: 'redux',
    },
    sass: {
      title: 'Sass',
      description: '',
      imageSrc: 'sass.svg',
      imageAlt: 'Sass logo',
      href: 'sass',
    },
    storybook: {
      title: 'Storybook',
      description: '',
      imageSrc: 'storybook.svg',
      imageAlt: 'Storybook logo',
      href: 'storybook',
    },
    strapi: {
      title: 'Strapi',
      description: '',
      imageSrc: 'strapi.svg',
      imageAlt: 'Strapi logo',
      href: 'strapi',
    },
    ['styled-components']: {
      title: 'Styled Components',
      description: '',
      imageSrc: 'styledcomponents.svg',
      imageAlt: 'Styled Components logo',
      href: 'styled-components',
    },
    svg: {
      title: 'SVG',
      description: '',
      imageSrc: 'svg.svg',
      imageAlt: 'SVG logo',
      href: 'svg',
    },
    tailwind: {
      title: 'Tailwind',
      description: '',
      imageSrc: 'tailwind.svg',
      imageAlt: 'Tailwind logo',
      href: 'tailwind',
    },
    typescript: {
      title: 'TypeScript',
      description: '',
      imageSrc: 'typescript.svg',
      imageAlt: 'TypeScript logo',
      href: 'typescript',
    },
    vite: {
      title: 'Vite',
      description: '',
      imageSrc: 'vite.svg',
      imageAlt: 'Vite logo',
      href: 'vite',
    },
    vscode: {
      title: 'VSCode',
      description: '',
      imageSrc: 'vscode.svg',
      imageAlt: 'VSCode logo',
      href: 'vscode',
    },
    webpack: {
      title: 'Webpack',
      description: '',
      imageSrc: 'webpack.svg',
      imageAlt: 'Webpack logo',
      href: 'webpack',
    },
    wordpress: {
      title: 'WordPress',
      description: '',
      imageSrc: 'wordpress.svg',
      imageAlt: 'WordPress logo',
      href: 'wordpress',
    },
    ['wp-graphql']: {
      title: 'WPGraphQL',
      description: '',
      imageSrc: 'wpgraphql.svg',
      imageAlt: 'WPGraphQL logo',
      href: 'wp-graphql',
    },
  },
} as const satisfies TechSkillItems;

export const techSkills = {
  da: Object.entries(skillsObject.da).map(([_key, value]) => value),
  en: Object.entries(skillsObject.en).map(([_key, value]) => value),
};
