import type { SkillInfo } from '@components/techSkillsMarquee/TechSkillsMarquee.astro';

type TechSkills = (typeof techSkillEntries)[number];

type TechSkillItems = {
  da: Record<TechSkills, SkillInfo>;
  en: Record<TechSkills, SkillInfo>;
};

/**
 * To add a new tech skill, add a new key to the techSkillEntries array and add info to the skillsObject.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const techSkillEntries = [
  'accessibility',
  'algolia',
  'apolloClient',
  'astro',
  'bash',
  'css',
  'docker',
  'figma',
  'gatsby',
  'git',
  'github',
  'gitlab',
  'graphql',
  'graphqlCodegen',
  'html',
  'inkscape',
  'javascript',
  'jest',
  'mantine',
  'nextjs',
  'playwright',
  'react',
  'reactNative',
  'reactTestingLibrary',
  'redux',
  'sass',
  'storybook',
  'strapi',
  'styledComponents',
  'svg',
  'tailwind',
  'typeScript',
  'vite',
  'vscode',
  'webpack',
  'wordPress',
  'wpGraphQL',
] as const;

/**
 *
 * //============================================
 * @example
 * // Template for adding a new skill item:
 * title: '',
 * description: '',
 * imageSrc: '',
 * imageAlt: '',
 * href: '',
 */
const skillsObject = {
  da: {
    accessibility: {
      title: 'Accessibility',
      description: '',
      imageSrc: 'accessibility.svg',
      imageAlt: 'Accessibility',
      href: 'accessibility',
    },
    algolia: {
      title: 'Algolia',
      description: '',
      imageSrc: 'algolia.svg',
      imageAlt: 'Algolia',
      href: 'algolia',
    },
    apolloClient: {
      title: 'Apollo Client',
      description: '',
      imageSrc: 'apolloclient.svg',
      imageAlt: 'Apollo Client',
      href: 'apolloclient',
    },
    astro: {
      title: 'Astro',
      description: '',
      imageSrc: 'astro.svg',
      imageAlt: '',
      href: '',
    },
    bash: {
      title: 'Bash',
      description: '',
      imageSrc: 'bash.svg',
      imageAlt: '',
      href: '',
    },
    css: {
      title: 'CSS',
      description: '',
      imageSrc: 'css.svg',
      imageAlt: '',
      href: '',
    },
    docker: {
      title: 'Docker',
      description: '',
      imageSrc: 'docker.svg',
      imageAlt: '',
      href: '',
    },
    figma: {
      title: 'Figma',
      description: '',
      imageSrc: 'figma.svg',
      imageAlt: '',
      href: '',
    },
    gatsby: {
      title: 'Gatsby',
      description: '',
      imageSrc: 'gatsby.svg',
      imageAlt: '',
      href: '',
    },
    git: {
      title: 'Git',
      description: '',
      imageSrc: 'git.svg',
      imageAlt: '',
      href: '',
    },
    github: {
      title: 'Github',
      description: '',
      imageSrc: 'github.svg',
      imageAlt: '',
      href: '',
    },
    gitlab: {
      title: 'Gitlab',
      description: '',
      imageSrc: 'gitlab.svg',
      imageAlt: '',
      href: '',
    },
    graphql: {
      title: 'GraphQL',
      description: '',
      imageSrc: 'graphql.svg',
      imageAlt: '',
      href: '',
    },
    graphqlCodegen: {
      title: 'GraphQL Codegen',
      description: '',
      imageSrc: 'graphqlcodegen.svg',
      imageAlt: '',
      href: '',
    },
    html: {
      title: 'HTML',
      description: '',
      imageSrc: 'html.svg',
      imageAlt: '',
      href: '',
    },
    inkscape: {
      title: 'Inkscape',
      description: '',
      imageSrc: 'inkscape.svg',
      imageAlt: '',
      href: '',
    },
    javascript: {
      title: 'JavaScript',
      description: '',
      imageSrc: 'javascript.svg',
      imageAlt: '',
      href: '',
    },
    jest: {
      title: 'Jest',
      description: '',
      imageSrc: 'jest.svg',
      imageAlt: '',
      href: '',
    },
    mantine: {
      title: 'Mantine',
      description: '',
      imageSrc: 'mantine.svg',
      imageAlt: '',
      href: '',
    },
    nextjs: {
      title: 'Next.js',
      description: '',
      imageSrc: 'nextjs.svg',
      imageAlt: '',
      href: '',
    },
    playwright: {
      title: 'Playwright',
      description: '',
      imageSrc: 'playwright.svg',
      imageAlt: '',
      href: '',
    },
    react: {
      title: 'React',
      description: '',
      imageSrc: 'react.svg',
      imageAlt: '',
      href: '',
    },
    reactNative: {
      title: 'React Native',
      description: '',
      imageSrc: 'reactnative.svg',
      imageAlt: '',
      href: '',
    },
    reactTestingLibrary: {
      title: 'React Testing Library',
      description: '',
      imageSrc: 'reacttestinglibrary.svg',
      imageAlt: '',
      href: '',
    },
    redux: {
      title: 'Redux',
      description: '',
      imageSrc: 'redux.svg',
      imageAlt: '',
      href: '',
    },
    sass: {
      title: 'Sass',
      description: '',
      imageSrc: 'sass.svg',
      imageAlt: '',
      href: '',
    },
    storybook: {
      title: 'Storybook',
      description: '',
      imageSrc: 'storybook.svg',
      imageAlt: '',
      href: '',
    },
    strapi: {
      title: 'Strapi',
      description: '',
      imageSrc: 'strapi.svg',
      imageAlt: '',
      href: '',
    },
    styledComponents: {
      title: 'Styled Components',
      description: '',
      imageSrc: 'styledcomponents.svg',
      imageAlt: '',
      href: '',
    },
    svg: {
      title: 'SVG',
      description: '',
      imageSrc: 'svg.svg',
      imageAlt: '',
      href: '',
    },
    tailwind: {
      title: 'Tailwind',
      description: '',
      imageSrc: 'tailwind.svg',
      imageAlt: '',
      href: '',
    },
    typeScript: {
      title: 'TypeScript',
      description: '',
      imageSrc: 'typescript.svg',
      imageAlt: '',
      href: '',
    },
    vite: {
      title: 'Vite',
      description: '',
      imageSrc: 'vite.svg',
      imageAlt: '',
      href: '',
    },
    vscode: {
      title: 'VSCode',
      description: '',
      imageSrc: 'vscode.svg',
      imageAlt: '',
      href: '',
    },
    webpack: {
      title: 'Webpack',
      description: '',
      imageSrc: 'webpack.svg',
      imageAlt: '',
      href: '',
    },
    wordPress: {
      title: 'WordPress',
      description: '',
      imageSrc: 'wordpress.svg',
      imageAlt: '',
      href: '',
    },
    wpGraphQL: {
      title: 'WPGraphQL',
      description: '',
      imageSrc: 'wpgraphql.svg',
      imageAlt: '',
      href: '',
    },
  },
  en: {
    accessibility: {
      title: 'Accessibility',
      description: '',
      imageSrc: 'accessibility.svg',
      imageAlt: 'Accessibility',
      href: 'accessibility',
    },
    algolia: {
      title: 'Algolia',
      description: '',
      imageSrc: 'algolia.svg',
      imageAlt: 'Algolia',
      href: 'algolia',
    },
    apolloClient: {
      title: 'Apollo Client',
      description: '',
      imageSrc: 'apolloclient.svg',
      imageAlt: 'Apollo Client',
      href: 'apolloclient',
    },
    astro: {
      title: 'Astro',
      description: '',
      imageSrc: 'astro.svg',
      imageAlt: '',
      href: '',
    },
    bash: {
      title: 'Bash',
      description: '',
      imageSrc: 'bash.svg',
      imageAlt: '',
      href: '',
    },
    css: {
      title: 'CSS',
      description: '',
      imageSrc: 'css.svg',
      imageAlt: '',
      href: '',
    },
    docker: {
      title: 'Docker',
      description: '',
      imageSrc: 'docker.svg',
      imageAlt: '',
      href: '',
    },
    figma: {
      title: 'Figma',
      description: '',
      imageSrc: 'figma.svg',
      imageAlt: '',
      href: '',
    },
    gatsby: {
      title: 'Gatsby',
      description: '',
      imageSrc: 'gatsby.svg',
      imageAlt: '',
      href: '',
    },
    git: {
      title: 'Git',
      description: '',
      imageSrc: 'git.svg',
      imageAlt: '',
      href: '',
    },
    github: {
      title: 'Github',
      description: '',
      imageSrc: 'github.svg',
      imageAlt: '',
      href: '',
    },
    gitlab: {
      title: 'Gitlab',
      description: '',
      imageSrc: 'gitlab.svg',
      imageAlt: '',
      href: '',
    },
    graphql: {
      title: 'GraphQL',
      description: '',
      imageSrc: 'graphql.svg',
      imageAlt: '',
      href: '',
    },
    graphqlCodegen: {
      title: 'GraphQL Codegen',
      description: '',
      imageSrc: 'graphqlcodegen.svg',
      imageAlt: '',
      href: '',
    },
    html: {
      title: 'HTML',
      description: '',
      imageSrc: 'html.svg',
      imageAlt: '',
      href: '',
    },
    inkscape: {
      title: 'Inkscape',
      description: '',
      imageSrc: 'inkscape.svg',
      imageAlt: '',
      href: '',
    },
    javascript: {
      title: 'JavaScript',
      description: '',
      imageSrc: 'javascript.svg',
      imageAlt: '',
      href: '',
    },
    jest: {
      title: 'Jest',
      description: '',
      imageSrc: 'jest.svg',
      imageAlt: '',
      href: '',
    },
    mantine: {
      title: 'Mantine',
      description: '',
      imageSrc: 'mantine.svg',
      imageAlt: '',
      href: '',
    },
    nextjs: {
      title: 'Next.js',
      description: '',
      imageSrc: 'nextjs.svg',
      imageAlt: '',
      href: '',
    },
    playwright: {
      title: 'Playwright',
      description: '',
      imageSrc: 'playwright.svg',
      imageAlt: '',
      href: '',
    },
    react: {
      title: 'React',
      description: '',
      imageSrc: 'react.svg',
      imageAlt: '',
      href: '',
    },
    reactNative: {
      title: 'React Native',
      description: '',
      imageSrc: 'reactnative.svg',
      imageAlt: '',
      href: '',
    },
    reactTestingLibrary: {
      title: 'React Testing Library',
      description: '',
      imageSrc: 'reacttestinglibrary.svg',
      imageAlt: '',
      href: '',
    },
    redux: {
      title: 'Redux',
      description: '',
      imageSrc: 'redux.svg',
      imageAlt: '',
      href: '',
    },
    sass: {
      title: 'Sass',
      description: '',
      imageSrc: 'sass.svg',
      imageAlt: '',
      href: '',
    },
    storybook: {
      title: 'Storybook',
      description: '',
      imageSrc: 'storybook.svg',
      imageAlt: '',
      href: '',
    },
    strapi: {
      title: 'Strapi',
      description: '',
      imageSrc: 'strapi.svg',
      imageAlt: '',
      href: '',
    },
    styledComponents: {
      title: 'Styled Components',
      description: '',
      imageSrc: 'styledcomponents.svg',
      imageAlt: '',
      href: '',
    },
    svg: {
      title: 'SVG',
      description: '',
      imageSrc: 'svg.svg',
      imageAlt: '',
      href: '',
    },
    tailwind: {
      title: 'Tailwind',
      description: '',
      imageSrc: 'tailwind.svg',
      imageAlt: '',
      href: '',
    },
    typeScript: {
      title: 'TypeScript',
      description: '',
      imageSrc: 'typescript.svg',
      imageAlt: '',
      href: '',
    },
    vite: {
      title: 'Vite',
      description: '',
      imageSrc: 'vite.svg',
      imageAlt: '',
      href: '',
    },
    vscode: {
      title: 'VSCode',
      description: '',
      imageSrc: 'vscode.svg',
      imageAlt: '',
      href: '',
    },
    webpack: {
      title: 'Webpack',
      description: '',
      imageSrc: 'webpack.svg',
      imageAlt: '',
      href: '',
    },
    wordPress: {
      title: 'WordPress',
      description: '',
      imageSrc: 'wordpress.svg',
      imageAlt: '',
      href: '',
    },
    wpGraphQL: {
      title: 'WPGraphQL',
      description: '',
      imageSrc: 'wpgraphql.svg',
      imageAlt: '',
      href: '',
    },
  },
} as const satisfies TechSkillItems;

export const techSkills = {
  da: Object.entries(skillsObject.da).map(([_key, value]) => value),
  en: Object.entries(skillsObject.en).map(([_key, value]) => value),
};
