/**
* THIS FILE IS AUTOGENERATED!
* To make changes please run the 'generateRoutes' script from package.json
*/

export const routes = {
  "contact": {
    "url": "contact",
    "alternates": [
      {
        "url": "da/kontakt",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kontakt": {
    "url": "da/kontakt",
    "alternates": [
      {
        "url": "contact",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "message-received": {
    "url": "message-received",
    "alternates": [
      {
        "url": "da/besked-modtaget",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/besked-modtaget": {
    "url": "da/besked-modtaget",
    "alternates": [
      {
        "url": "message-received",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "message-error": {
    "url": "message-error",
    "alternates": [
      {
        "url": "da/besked-fejl",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/besked-fejl": {
    "url": "da/besked-fejl",
    "alternates": [
      {
        "url": "message-error",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "share": {
    "url": "share",
    "alternates": [
      {
        "url": "da/del",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/del": {
    "url": "da/del",
    "alternates": [
      {
        "url": "share",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "work": {
    "url": "work",
    "alternates": [
      {
        "url": "da/arbejde",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arbejde": {
    "url": "da/arbejde",
    "alternates": [
      {
        "url": "work",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills": {
    "url": "skills",
    "alternates": [
      {
        "url": "da/kompetencer",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer": {
    "url": "da/kompetencer",
    "alternates": [
      {
        "url": "skills",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about": {
    "url": "about",
    "alternates": [
      {
        "url": "da/om-mig",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig": {
    "url": "da/om-mig",
    "alternates": [
      {
        "url": "about",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "archive": {
    "url": "archive",
    "alternates": [
      {
        "url": "da/arkiv",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arkiv": {
    "url": "da/arkiv",
    "alternates": [
      {
        "url": "archive",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "email-reply": {
    "url": "email-reply",
    "alternates": [
      {
        "url": "da/email-svar",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/email-svar": {
    "url": "da/email-svar",
    "alternates": [
      {
        "url": "email-reply",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "work/contact": {
    "url": "work/contact",
    "alternates": [
      {
        "url": "da/arbejde/kontakt",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arbejde/kontakt": {
    "url": "da/arbejde/kontakt",
    "alternates": [
      {
        "url": "work/contact",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "work/message-received": {
    "url": "work/message-received",
    "alternates": [
      {
        "url": "da/arbejde/besked-modtaget",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arbejde/besked-modtaget": {
    "url": "da/arbejde/besked-modtaget",
    "alternates": [
      {
        "url": "work/message-received",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "work/message-error": {
    "url": "work/message-error",
    "alternates": [
      {
        "url": "da/arbejde/besked-fejl",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arbejde/besked-fejl": {
    "url": "da/arbejde/besked-fejl",
    "alternates": [
      {
        "url": "work/message-error",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "work/share": {
    "url": "work/share",
    "alternates": [
      {
        "url": "da/arbejde/del",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arbejde/del": {
    "url": "da/arbejde/del",
    "alternates": [
      {
        "url": "work/share",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/contact": {
    "url": "skills/contact",
    "alternates": [
      {
        "url": "da/kompetencer/kontakt",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/kontakt": {
    "url": "da/kompetencer/kontakt",
    "alternates": [
      {
        "url": "skills/contact",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/message-received": {
    "url": "skills/message-received",
    "alternates": [
      {
        "url": "da/kompetencer/besked-modtaget",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/besked-modtaget": {
    "url": "da/kompetencer/besked-modtaget",
    "alternates": [
      {
        "url": "skills/message-received",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/message-error": {
    "url": "skills/message-error",
    "alternates": [
      {
        "url": "da/kompetencer/besked-fejl",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/besked-fejl": {
    "url": "da/kompetencer/besked-fejl",
    "alternates": [
      {
        "url": "skills/message-error",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/share": {
    "url": "skills/share",
    "alternates": [
      {
        "url": "da/kompetencer/del",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/del": {
    "url": "da/kompetencer/del",
    "alternates": [
      {
        "url": "skills/share",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/accessibility": {
    "url": "skills/accessibility",
    "alternates": [
      {
        "url": "da/kompetencer/accessibility",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/accessibility": {
    "url": "da/kompetencer/accessibility",
    "alternates": [
      {
        "url": "skills/accessibility",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/algolia": {
    "url": "skills/algolia",
    "alternates": [
      {
        "url": "da/kompetencer/algolia",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/algolia": {
    "url": "da/kompetencer/algolia",
    "alternates": [
      {
        "url": "skills/algolia",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/apollo-client": {
    "url": "skills/apollo-client",
    "alternates": [
      {
        "url": "da/kompetencer/apollo-client",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/apollo-client": {
    "url": "da/kompetencer/apollo-client",
    "alternates": [
      {
        "url": "skills/apollo-client",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/astro": {
    "url": "skills/astro",
    "alternates": [
      {
        "url": "da/kompetencer/astro",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/astro": {
    "url": "da/kompetencer/astro",
    "alternates": [
      {
        "url": "skills/astro",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/bash": {
    "url": "skills/bash",
    "alternates": [
      {
        "url": "da/kompetencer/bash",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/bash": {
    "url": "da/kompetencer/bash",
    "alternates": [
      {
        "url": "skills/bash",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/css": {
    "url": "skills/css",
    "alternates": [
      {
        "url": "da/kompetencer/css",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/css": {
    "url": "da/kompetencer/css",
    "alternates": [
      {
        "url": "skills/css",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/docker": {
    "url": "skills/docker",
    "alternates": [
      {
        "url": "da/kompetencer/docker",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/docker": {
    "url": "da/kompetencer/docker",
    "alternates": [
      {
        "url": "skills/docker",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/figma": {
    "url": "skills/figma",
    "alternates": [
      {
        "url": "da/kompetencer/figma",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/figma": {
    "url": "da/kompetencer/figma",
    "alternates": [
      {
        "url": "skills/figma",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/gatsby": {
    "url": "skills/gatsby",
    "alternates": [
      {
        "url": "da/kompetencer/gatsby",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/gatsby": {
    "url": "da/kompetencer/gatsby",
    "alternates": [
      {
        "url": "skills/gatsby",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/git": {
    "url": "skills/git",
    "alternates": [
      {
        "url": "da/kompetencer/git",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/git": {
    "url": "da/kompetencer/git",
    "alternates": [
      {
        "url": "skills/git",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/github": {
    "url": "skills/github",
    "alternates": [
      {
        "url": "da/kompetencer/github",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/github": {
    "url": "da/kompetencer/github",
    "alternates": [
      {
        "url": "skills/github",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/gitlab": {
    "url": "skills/gitlab",
    "alternates": [
      {
        "url": "da/kompetencer/gitlab",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/gitlab": {
    "url": "da/kompetencer/gitlab",
    "alternates": [
      {
        "url": "skills/gitlab",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/graphql": {
    "url": "skills/graphql",
    "alternates": [
      {
        "url": "da/kompetencer/graphql",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/graphql": {
    "url": "da/kompetencer/graphql",
    "alternates": [
      {
        "url": "skills/graphql",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/graphql-codegen": {
    "url": "skills/graphql-codegen",
    "alternates": [
      {
        "url": "da/kompetencer/graphql-codegen",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/graphql-codegen": {
    "url": "da/kompetencer/graphql-codegen",
    "alternates": [
      {
        "url": "skills/graphql-codegen",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/html": {
    "url": "skills/html",
    "alternates": [
      {
        "url": "da/kompetencer/html",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/html": {
    "url": "da/kompetencer/html",
    "alternates": [
      {
        "url": "skills/html",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/inkscape": {
    "url": "skills/inkscape",
    "alternates": [
      {
        "url": "da/kompetencer/inkscape",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/inkscape": {
    "url": "da/kompetencer/inkscape",
    "alternates": [
      {
        "url": "skills/inkscape",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/javascript": {
    "url": "skills/javascript",
    "alternates": [
      {
        "url": "da/kompetencer/javascript",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/javascript": {
    "url": "da/kompetencer/javascript",
    "alternates": [
      {
        "url": "skills/javascript",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/jest": {
    "url": "skills/jest",
    "alternates": [
      {
        "url": "da/kompetencer/jest",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/jest": {
    "url": "da/kompetencer/jest",
    "alternates": [
      {
        "url": "skills/jest",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/mantine": {
    "url": "skills/mantine",
    "alternates": [
      {
        "url": "da/kompetencer/mantine",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/mantine": {
    "url": "da/kompetencer/mantine",
    "alternates": [
      {
        "url": "skills/mantine",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/nextjs": {
    "url": "skills/nextjs",
    "alternates": [
      {
        "url": "da/kompetencer/nextjs",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/nextjs": {
    "url": "da/kompetencer/nextjs",
    "alternates": [
      {
        "url": "skills/nextjs",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/playwright": {
    "url": "skills/playwright",
    "alternates": [
      {
        "url": "da/kompetencer/playwright",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/playwright": {
    "url": "da/kompetencer/playwright",
    "alternates": [
      {
        "url": "skills/playwright",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/react": {
    "url": "skills/react",
    "alternates": [
      {
        "url": "da/kompetencer/react",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/react": {
    "url": "da/kompetencer/react",
    "alternates": [
      {
        "url": "skills/react",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/react-native": {
    "url": "skills/react-native",
    "alternates": [
      {
        "url": "da/kompetencer/react-native",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/react-native": {
    "url": "da/kompetencer/react-native",
    "alternates": [
      {
        "url": "skills/react-native",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/react-testing-library": {
    "url": "skills/react-testing-library",
    "alternates": [
      {
        "url": "da/kompetencer/react-testing-library",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/react-testing-library": {
    "url": "da/kompetencer/react-testing-library",
    "alternates": [
      {
        "url": "skills/react-testing-library",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/redux": {
    "url": "skills/redux",
    "alternates": [
      {
        "url": "da/kompetencer/redux",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/redux": {
    "url": "da/kompetencer/redux",
    "alternates": [
      {
        "url": "skills/redux",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/sass": {
    "url": "skills/sass",
    "alternates": [
      {
        "url": "da/kompetencer/sass",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/sass": {
    "url": "da/kompetencer/sass",
    "alternates": [
      {
        "url": "skills/sass",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/storybook": {
    "url": "skills/storybook",
    "alternates": [
      {
        "url": "da/kompetencer/storybook",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/storybook": {
    "url": "da/kompetencer/storybook",
    "alternates": [
      {
        "url": "skills/storybook",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/strapi": {
    "url": "skills/strapi",
    "alternates": [
      {
        "url": "da/kompetencer/strapi",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/strapi": {
    "url": "da/kompetencer/strapi",
    "alternates": [
      {
        "url": "skills/strapi",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/styled-components": {
    "url": "skills/styled-components",
    "alternates": [
      {
        "url": "da/kompetencer/styled-components",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/styled-components": {
    "url": "da/kompetencer/styled-components",
    "alternates": [
      {
        "url": "skills/styled-components",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/svg": {
    "url": "skills/svg",
    "alternates": [
      {
        "url": "da/kompetencer/svg",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/svg": {
    "url": "da/kompetencer/svg",
    "alternates": [
      {
        "url": "skills/svg",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/tailwind": {
    "url": "skills/tailwind",
    "alternates": [
      {
        "url": "da/kompetencer/tailwind",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/tailwind": {
    "url": "da/kompetencer/tailwind",
    "alternates": [
      {
        "url": "skills/tailwind",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/typescript": {
    "url": "skills/typescript",
    "alternates": [
      {
        "url": "da/kompetencer/typescript",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/typescript": {
    "url": "da/kompetencer/typescript",
    "alternates": [
      {
        "url": "skills/typescript",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/vite": {
    "url": "skills/vite",
    "alternates": [
      {
        "url": "da/kompetencer/vite",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/vite": {
    "url": "da/kompetencer/vite",
    "alternates": [
      {
        "url": "skills/vite",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/vscode": {
    "url": "skills/vscode",
    "alternates": [
      {
        "url": "da/kompetencer/vscode",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/vscode": {
    "url": "da/kompetencer/vscode",
    "alternates": [
      {
        "url": "skills/vscode",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/webpack": {
    "url": "skills/webpack",
    "alternates": [
      {
        "url": "da/kompetencer/webpack",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/webpack": {
    "url": "da/kompetencer/webpack",
    "alternates": [
      {
        "url": "skills/webpack",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/wordpress": {
    "url": "skills/wordpress",
    "alternates": [
      {
        "url": "da/kompetencer/wordpress",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/wordpress": {
    "url": "da/kompetencer/wordpress",
    "alternates": [
      {
        "url": "skills/wordpress",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "skills/wp-graphql": {
    "url": "skills/wp-graphql",
    "alternates": [
      {
        "url": "da/kompetencer/wp-graphql",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/kompetencer/wp-graphql": {
    "url": "da/kompetencer/wp-graphql",
    "alternates": [
      {
        "url": "skills/wp-graphql",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/cycling-hjorring-2011": {
    "url": "about/cycling-hjorring-2011",
    "alternates": [
      {
        "url": "da/om-mig/cykling-hjorring-2011",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/cykling-hjorring-2011": {
    "url": "da/om-mig/cykling-hjorring-2011",
    "alternates": [
      {
        "url": "about/cycling-hjorring-2011",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/cyclocross-2009": {
    "url": "about/cyclocross-2009",
    "alternates": [
      {
        "url": "da/om-mig/cykelcross-2009",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/cykelcross-2009": {
    "url": "da/om-mig/cykelcross-2009",
    "alternates": [
      {
        "url": "about/cyclocross-2009",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/cycling-hammel-2007": {
    "url": "about/cycling-hammel-2007",
    "alternates": [
      {
        "url": "da/om-mig/cykellob-hammel-2007",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/cykellob-hammel-2007": {
    "url": "da/om-mig/cykellob-hammel-2007",
    "alternates": [
      {
        "url": "about/cycling-hammel-2007",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/sonderborg-2009": {
    "url": "about/sonderborg-2009",
    "alternates": [
      {
        "url": "da/om-mig/sonderborg-2009",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/sonderborg-2009": {
    "url": "da/om-mig/sonderborg-2009",
    "alternates": [
      {
        "url": "about/sonderborg-2009",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/nice-2009": {
    "url": "about/nice-2009",
    "alternates": [
      {
        "url": "da/om-mig/nice-2009",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/nice-2009": {
    "url": "da/om-mig/nice-2009",
    "alternates": [
      {
        "url": "about/nice-2009",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/esbjerg-2017": {
    "url": "about/esbjerg-2017",
    "alternates": [
      {
        "url": "da/om-mig/esbjerg-2017",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/esbjerg-2017": {
    "url": "da/om-mig/esbjerg-2017",
    "alternates": [
      {
        "url": "about/esbjerg-2017",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/half-marathon-aarhus-2015": {
    "url": "about/half-marathon-aarhus-2015",
    "alternates": [
      {
        "url": "da/om-mig/half-marathon-aarhus-2015",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/half-marathon-aarhus-2015": {
    "url": "da/om-mig/half-marathon-aarhus-2015",
    "alternates": [
      {
        "url": "about/half-marathon-aarhus-2015",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/marselislobet-aarhus-2015": {
    "url": "about/marselislobet-aarhus-2015",
    "alternates": [
      {
        "url": "da/om-mig/marselislobet-aarhus-2015",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/marselislobet-aarhus-2015": {
    "url": "da/om-mig/marselislobet-aarhus-2015",
    "alternates": [
      {
        "url": "about/marselislobet-aarhus-2015",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/aarhus-track-race-2017": {
    "url": "about/aarhus-track-race-2017",
    "alternates": [
      {
        "url": "da/om-mig/aarhus-track-race-2017",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/aarhus-track-race-2017": {
    "url": "da/om-mig/aarhus-track-race-2017",
    "alternates": [
      {
        "url": "about/aarhus-track-race-2017",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/hannover-marathon-2016-2": {
    "url": "about/hannover-marathon-2016-2",
    "alternates": [
      {
        "url": "da/om-mig/hannover-marathon-2016-2",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/hannover-marathon-2016-2": {
    "url": "da/om-mig/hannover-marathon-2016-2",
    "alternates": [
      {
        "url": "about/hannover-marathon-2016-2",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/hannover-marathon-2016-1": {
    "url": "about/hannover-marathon-2016-1",
    "alternates": [
      {
        "url": "da/om-mig/hannover-marathon-2016-1",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/hannover-marathon-2016-1": {
    "url": "da/om-mig/hannover-marathon-2016-1",
    "alternates": [
      {
        "url": "about/hannover-marathon-2016-1",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/contact": {
    "url": "about/contact",
    "alternates": [
      {
        "url": "da/om-mig/kontakt",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/kontakt": {
    "url": "da/om-mig/kontakt",
    "alternates": [
      {
        "url": "about/contact",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/message-received": {
    "url": "about/message-received",
    "alternates": [
      {
        "url": "da/om-mig/besked-modtaget",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/besked-modtaget": {
    "url": "da/om-mig/besked-modtaget",
    "alternates": [
      {
        "url": "about/message-received",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/message-error": {
    "url": "about/message-error",
    "alternates": [
      {
        "url": "da/om-mig/besked-fejl",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/besked-fejl": {
    "url": "da/om-mig/besked-fejl",
    "alternates": [
      {
        "url": "about/message-error",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "about/share": {
    "url": "about/share",
    "alternates": [
      {
        "url": "da/om-mig/del",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/om-mig/del": {
    "url": "da/om-mig/del",
    "alternates": [
      {
        "url": "about/share",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "archive/contact": {
    "url": "archive/contact",
    "alternates": [
      {
        "url": "da/arkiv/kontakt",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arkiv/kontakt": {
    "url": "da/arkiv/kontakt",
    "alternates": [
      {
        "url": "archive/contact",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "archive/message-received": {
    "url": "archive/message-received",
    "alternates": [
      {
        "url": "da/arkiv/besked-modtaget",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arkiv/besked-modtaget": {
    "url": "da/arkiv/besked-modtaget",
    "alternates": [
      {
        "url": "archive/message-received",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "archive/message-error": {
    "url": "archive/message-error",
    "alternates": [
      {
        "url": "da/arkiv/besked-fejl",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arkiv/besked-fejl": {
    "url": "da/arkiv/besked-fejl",
    "alternates": [
      {
        "url": "archive/message-error",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  },
  "archive/share": {
    "url": "archive/share",
    "alternates": [
      {
        "url": "da/arkiv/del",
        "lang": "da",
        "hreflang": "da-DK"
      }
    ]
  },
  "da/arkiv/del": {
    "url": "da/arkiv/del",
    "alternates": [
      {
        "url": "archive/share",
        "hreflang": "en-US",
        "lang": "en"
      }
    ]
  }
};